"use client";
import { useEffect, useRef, useState } from "react";
import { AudioLines, ArrowLeftRight, Mic, Square, LockKeyhole, Send, Volume2, Headphones, Languages } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
type Message={id:string;role:"user"|"assistant";text:string};type Locale="ko"|"ja"|"en";type Phase="ready"|"listening"|"translating"|"speaking";
const COPY={
 ko:{title:"한일 실시간 통역",pin:"PIN 보호",eyebrow:"DIRECT TRANSLATION",heading:"우리의 대화, 언어의 경계 없이.",connected:"연결됨",connecting:"연결 중",offline:"연결 전",korean:"한국어",japanese:"日本語",auto:"자동 감지",empty:"메시지처럼 가볍게, 통역을 시작하세요.",emptyBody:<>한국어로 말하면 일본어로,<br/>일본어로 말하면 한국어로 들려드려요.</>,example:"통역 예시",source:"원문",translation:"통역",hearing:"음성을 듣고 있어요…",ready:"대화할 준비가 되었나요?",readySub:"시작 버튼을 누르고 편하게 말씀하세요",listening:"듣고 있어요",translating:"통역하고 있어요",speaking:"통역을 들려드려요",activeSub:"통역이 끝나면 이어서 말씀해 주세요",start:"통역 시작",cancel:"연결 취소",stop:"통역 종료",typeActive:"말 대신 글로 입력해도 좋아요",typeInactive:"통역을 시작한 후 글로도 대화할 수 있어요",headphones:"이어폰을 사용하면 더 선명해요",sound:"음성 출력",based:"OpenAI Realtime 기반 · AI 음성 통역",retained:"대화는 이 창에서만 유지됩니다.",pinTitle:"PIN Number 입력",pinDesc:"4자리 PIN을 입력하면 통역이 시작됩니다.",checking:"확인 중…",confirm:"확인하고 통역 시작",pinNote:<>PIN 확인 후 마이크 사용을 허용해 주세요.<br/>음성과 메시지는 통역을 위해 OpenAI로 전송됩니다.</>,audio:"통역 소리 재생 허용",genericError:"통역 요청 중 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.",textError:"문자 통역에 실패했습니다. 잠시 후 다시 입력해 주세요.",lang:"페이지 언어"},
 ja:{title:"日韓リアルタイム通訳",pin:"PIN保護",eyebrow:"DIRECT TRANSLATION",heading:"言葉の壁を越えて、会話をもっと自由に。",connected:"接続済み",connecting:"接続中",offline:"未接続",korean:"韓国語",japanese:"日本語",auto:"自動検出",empty:"メッセージを送るように、気軽に通訳。",emptyBody:<>韓国語で話すと日本語に、<br/>日本語で話すと韓国語に通訳します。</>,example:"通訳例",source:"原文",translation:"通訳",hearing:"音声を聞いています…",ready:"会話を始めますか？",readySub:"開始ボタンを押して、そのまま話してください",listening:"聞いています",translating:"通訳しています",speaking:"通訳音声を再生しています",activeSub:"通訳が終わってから続けて話してください",start:"通訳を開始",cancel:"接続をキャンセル",stop:"通訳を終了",typeActive:"文字を入力して通訳することもできます",typeInactive:"通訳を開始すると文字でも会話できます",headphones:"イヤホンを使うとより明瞭です",sound:"音声出力",based:"OpenAI Realtime · AI音声通訳",retained:"会話はこの画面内だけに保持されます。",pinTitle:"PIN Numberを入力",pinDesc:"4桁のPINを入力すると通訳が始まります。",checking:"確認中…",confirm:"確認して通訳を開始",pinNote:<>PIN確認後、マイクの使用を許可してください。<br/>音声とメッセージは通訳のためOpenAIに送信されます。</>,audio:"通訳音声の再生を許可",genericError:"通訳中にエラーが発生しました。しばらくしてから再試行してください。",textError:"文字の通訳に失敗しました。しばらくしてからもう一度入力してください。",lang:"表示言語"},
 en:{title:"Korean–Japanese Live Interpreter",pin:"PIN protected",eyebrow:"DIRECT TRANSLATION",heading:"One conversation, beyond language barriers.",connected:"Connected",connecting:"Connecting",offline:"Not connected",korean:"Korean",japanese:"Japanese",auto:"Auto detect",empty:"Translate as easily as sending a message.",emptyBody:<>Speak Korean to hear Japanese,<br/>or Japanese to hear Korean.</>,example:"Example",source:"Original",translation:"Translation",hearing:"Listening to audio…",ready:"Ready to talk?",readySub:"Press Start and speak naturally",listening:"Listening",translating:"Translating",speaking:"Playing translation",activeSub:"Continue after the translation finishes",start:"Start interpreting",cancel:"Cancel",stop:"Stop interpreting",typeActive:"You can also type a message to translate",typeInactive:"Start interpreting to use text messages",headphones:"Headphones make the audio clearer",sound:"Voice output",based:"Powered by OpenAI Realtime · AI interpreting",retained:"This conversation stays in this window.",pinTitle:"Enter PIN Number",pinDesc:"Enter the four-digit PIN to start interpreting.",checking:"Checking…",confirm:"Verify and start",pinNote:<>Allow microphone access after PIN verification.<br/>Audio and messages are sent to OpenAI for translation.</>,audio:"Allow translated audio",genericError:"An interpreting error occurred. Please try again shortly.",textError:"Text translation failed. Please try entering it again shortly.",lang:"Page language"}
};
export default function Home(){
 const [locale,setLocale]=useState<Locale>("ko"),[messages,setMessages]=useState<Message[]>([]),[status,setStatus]=useState("idle"),[phase,setPhase]=useState<Phase>("ready"),[error,setError]=useState(""),[pin,setPin]=useState(""),[settings,setSettings]=useState(false),[checking,setChecking]=useState(false),[pinError,setPinError]=useState(""),[sound,setSound]=useState(true),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[textBusy,setTextBusy]=useState(false),[audioBlocked,setAudioBlocked]=useState(false);
 const pc=useRef<RTCPeerConnection|null>(null),channel=useRef<RTCDataChannel|null>(null),stream=useRef<MediaStream|null>(null),audio=useRef<HTMLAudioElement|null>(null),abort=useRef<AbortController|null>(null),generation=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|null>(null),bottom=useRef<HTMLDivElement>(null),textToken=useRef("");const t=COPY[locale];
 const active=status==="connected",connecting=status==="connecting";
 function cleanup(){generation.current++;abort.current?.abort();if(timer.current)clearTimeout(timer.current);const old=pc.current;pc.current=null;channel.current?.close();channel.current=null;old?.close();stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;if(audio.current){audio.current.pause();audio.current.srcObject=null;}textToken.current="";setStatus("idle");setBusy(false);setTextBusy(false);setAudioBlocked(false);}
 useEffect(()=>{const saved=localStorage.getItem("sai-locale");if(saved==="ko"||saved==="ja"||saved==="en")setLocale(saved);return()=>{generation.current++;abort.current?.abort();if(timer.current)clearTimeout(timer.current);pc.current?.close();stream.current?.getTracks().forEach(track=>track.stop());};},[]);
 useEffect(()=>{document.documentElement.lang=locale;localStorage.setItem("sai-locale",locale);},[locale]);useEffect(()=>{if(audio.current)audio.current.muted=!sound;},[sound]);useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"});},[messages]);
 function update(id:string,role:Message["role"],text:string,append=false){if(!id)return;setMessages(prev=>{const found=prev.find(m=>m.id===id);return found?prev.map(m=>m.id===id?{...m,text:append?m.text+text:text}:m):[...prev,{id,role,text}];});}
 async function start(ticket:string){if(connecting||active)return;setError("");setStatus("connecting");const run=++generation.current;try{
  if(!navigator.mediaDevices?.getUserMedia)throw Error(locale==="ja"?"このブラウザではマイクを使用できません。ChromeまたはSafariで開いてください。":locale==="en"?"This browser cannot access the microphone. Open the site in Chrome or Safari.":"이 브라우저에서 마이크를 사용할 수 없습니다. Chrome 또는 Safari에서 열어 주세요.");
  const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(run!==generation.current){media.getTracks().forEach(track=>track.stop());return;}stream.current=media;const peer=new RTCPeerConnection();pc.current=peer;media.getTracks().forEach(track=>peer.addTrack(track,media));
  peer.ontrack=e=>{if(audio.current){audio.current.srcObject=e.streams[0]??new MediaStream([e.track]);audio.current.play().catch(()=>setAudioBlocked(true));}};peer.onconnectionstatechange=()=>{if(pc.current===peer&&["failed","disconnected"].includes(peer.connectionState)){cleanup();setError(t.genericError);}};
  const dc=peer.createDataChannel("oai-events");channel.current=dc;dc.onopen=()=>{if(run!==generation.current)return;if(timer.current)clearTimeout(timer.current);setStatus("connected");setPhase("ready");};dc.onclose=()=>{if(pc.current===peer){cleanup();setError(t.genericError);}};
  dc.onmessage=event=>{let e;try{e=JSON.parse(event.data);}catch{return;}if(e.type==="input_audio_buffer.speech_started"){setPhase("listening");update(e.item_id,"user","");}if(e.type==="input_audio_buffer.speech_stopped")setPhase("translating");if(e.type==="conversation.item.input_audio_transcription.completed")update(e.item_id,"user",e.transcript);if(e.type==="conversation.item.input_audio_transcription.failed")update(e.item_id,"user",t.hearing);if(e.type==="response.created")setBusy(true);if(e.type==="response.output_audio_transcript.delta"||e.type==="response.output_text.delta")update(e.item_id,"assistant",e.delta,true);if(e.type==="response.output_audio_transcript.done"||e.type==="response.output_text.done")update(e.item_id,"assistant",e.transcript??e.text);if(e.type==="response.done"){setBusy(false);if(e.response?.status==="failed")setError(t.genericError);}if(e.type==="output_audio_buffer.started"){setPhase("speaking");stream.current?.getAudioTracks().forEach(track=>track.enabled=false);}if(e.type==="output_audio_buffer.stopped"||e.type==="output_audio_buffer.cleared"){stream.current?.getAudioTracks().forEach(track=>track.enabled=true);setPhase("ready");}if(e.type==="error"){setBusy(false);setError(t.genericError);cleanup();}};
  timer.current=setTimeout(()=>{if(run===generation.current){cleanup();setError(t.genericError);}},30000);const offer=await peer.createOffer();await peer.setLocalDescription(offer);const controller=new AbortController();abort.current=controller;const response=await fetch("/api/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sdp:offer.sdp,ticket,locale}),signal:controller.signal});if(!response.ok){const body=await response.json();throw Error(body.error||t.genericError);}const sdp=await response.text();if(run!==generation.current)return;await peer.setRemoteDescription({type:"answer",sdp});
 }catch(e){if(run!==generation.current)return;cleanup();setError(e instanceof DOMException&&e.name==="NotAllowedError"?(locale==="ja"?"マイクの使用を許可してください。":locale==="en"?"Please allow microphone access in your browser settings.":"마이크 사용을 허용해 주세요. 브라우저 권한 설정에서 변경할 수 있습니다."):e instanceof Error?e.message:t.genericError);}}
 async function unlock(){if(pin.length!==4||checking)return;setChecking(true);setPinError("");try{const response=await fetch("/api/unlock",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pin,locale}),signal:AbortSignal.timeout(15000)});const body=await response.json();if(!response.ok)throw Error(body.error||t.genericError);textToken.current=body.textToken;setPin("");setSettings(false);await start(body.ticket);}catch(e){textToken.current="";setPinError(e instanceof Error?e.message:t.genericError);setPin("");}finally{setChecking(false);}}
 function promptPin(){setPin("");setPinError("");setSettings(true);}async function send(){const text=input.trim(),token=textToken.current;if(!text||!active||textBusy||!token)return;const userId="local_"+crypto.randomUUID(),translationId="translated_"+crypto.randomUUID();update(userId,"user",text);setInput("");setError("");setTextBusy(true);try{const response=await fetch("/api/translate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,token,locale}),signal:AbortSignal.timeout(35000)});const body=await response.json();if(!response.ok)throw Error(body.error||t.textError);update(translationId,"assistant",body.translation);}catch(e){setError(e instanceof Error?e.message:t.textError);}finally{setTextBusy(false);}}
 const phaseText=phase==="listening"?t.listening:phase==="translating"?t.translating:phase==="speaking"?t.speaking:t.ready;
 return <div className="shell"><header className="topbar"><a className="brand" href="/" aria-label="sai"><span className="brand-icon"><AudioLines size={23}/></span><b>sai<span className="brand-jp">사이</span></b></a><div className="top-right"><span className="top-caption">{t.title}</span><Select value={locale} onValueChange={value=>setLocale(value as Locale)}><SelectTrigger className="locale-select" aria-label={t.lang}><Languages size={17}/><SelectValue/></SelectTrigger><SelectContent align="end"><SelectItem value="ko">한국어</SelectItem><SelectItem value="ja">日本語</SelectItem><SelectItem value="en">English</SelectItem></SelectContent></Select><span className="privacy-badge"><LockKeyhole size={17}/>{t.pin}</span></div></header>
 <main className="workspace"><div className="page-heading"><div><p className="eyebrow">{t.eyebrow}</p><h1>{t.heading}</h1></div><span className={"connection "+(active?"on":"")}><i/>{active?t.connected:connecting?t.connecting:t.offline}</span></div><section className="chat-card" aria-label={t.title}><div className="language-bar"><div><span className="language-symbol ko">가</span><span>{t.korean}<small>Korean</small></span></div><ArrowLeftRight className="swap" size={20}/><div><span className="language-symbol ja">あ</span><span>{t.japanese}<small>Japanese</small></span></div><span className="auto-label">{t.auto}</span></div>
 <div className="conversation" role="log" aria-live="polite">{messages.length===0?<div className="empty-state"><div className="empty-mark"><Send size={39} strokeWidth={1.4}/></div><h2>{t.empty}</h2><p>{t.emptyBody}</p><div className="example"><span>안녕하세요.</span><ArrowLeftRight size={15}/><span lang="ja">こんにちは。</span><small>{t.example}</small></div></div>:messages.map(m=><article key={m.id} className={"message "+m.role}><div className="message-meta">{m.role==="user"?t.source:t.translation}<span>{/[가-힣]/.test(m.text)?t.korean:/[ぁ-ヿ一-龯]/.test(m.text)?t.japanese:""}</span></div><div className="bubble" lang={/[가-힣]/.test(m.text)?"ko":"ja"}>{m.text||t.hearing}</div></article>)}<div ref={bottom}/></div>
 <div className="control-area">{error&&<p className="error" role="alert">{error}</p>}{audioBlocked&&<button className="audio-enable" onClick={()=>audio.current?.play().then(()=>setAudioBlocked(false)).catch(()=>setError(t.genericError))}>{t.audio}</button>}<div className="voice-controls"><div className="voice-status"><span className={"voice-indicator "+(active?"active":"")}><AudioLines size={21}/></span><div><strong>{active?phaseText:connecting?t.connecting:t.ready}</strong><small>{active?t.activeSub:t.readySub}</small></div></div><button className={"start-button "+(active?"stop":"")} onClick={()=>active||connecting?cleanup():promptPin()}>{active||connecting?<Square size={17}/>:<Mic size={19}/>}<span>{active?t.stop:connecting?t.cancel:t.start}</span></button></div>
 <form className="composer" onSubmit={e=>{e.preventDefault();send();}}><input aria-label={t.typeActive} placeholder={active?t.typeActive:t.typeInactive} value={input} onChange={e=>setInput(e.target.value)} disabled={!active} maxLength={4000}/><button type="submit" disabled={!active||textBusy||!input.trim()} aria-label={t.translation} aria-busy={textBusy}><Send size={18}/></button></form><div className="control-footer"><span><Headphones size={14}/>{t.headphones}</span><label htmlFor="sound"><Volume2 size={15}/>{t.sound}<Switch id="sound" checked={sound} onCheckedChange={setSound}/></label></div></div></section><footer className="footnote"><span>{t.based}</span><span>{t.retained}</span></footer></main><audio ref={audio} autoPlay hidden/>
 <Dialog open={settings} onOpenChange={open=>{if(!checking){setSettings(open);setPin("");setPinError("");}}}><DialogContent className="settings-dialog" showCloseButton={!checking}><div className="pin-icon"><LockKeyhole size={27}/></div><DialogTitle>{t.pinTitle}</DialogTitle><DialogDescription>{t.pinDesc}</DialogDescription><form className="pin-form" onSubmit={e=>{e.preventDefault();unlock();}}><InputOTP autoFocus aria-label={t.pinTitle} maxLength={4} inputMode="numeric" pattern="[0-9]*" value={pin} onChange={value=>setPin(value.replace(/\D/g,""))} disabled={checking} containerClassName="pin-boxes"><InputOTPGroup>{[0,1,2,3].map(index=><InputOTPSlot key={index} index={index}/>)}</InputOTPGroup></InputOTP>{pinError&&<p className="error" role="alert">{pinError}</p>}<button type="submit" className="start-button" disabled={pin.length!==4||checking}>{checking?t.checking:t.confirm}</button></form><p className="key-note">{t.pinNote}</p></DialogContent></Dialog></div>;
}
